/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-error": "#ffffff",
          "inverse-surface": "#213145",
          "error": "#ba1a1a",
          "on-secondary-fixed": "#001e2f",
          "surface-bright": "#f8f9ff",
          "on-primary": "#ffffff",
          "on-primary-fixed-variant": "#003ea8",
          "surface": "#f8f9ff",
          "primary-fixed": "#dbe1ff",
          "on-tertiary-fixed-variant": "#2f2ebe",
          "secondary-fixed": "#c9e6ff",
          "on-tertiary-fixed": "#07006c",
          "on-tertiary-container": "#f1eeff",
          "outline-variant": "#c3c6d7",
          "primary-container": "#2563eb",
          "tertiary": "#3e3fcc",
          "outline": "#737686",
          "error-container": "#ffdad6",
          "surface-container-highest": "#d3e4fe",
          "on-background": "#0b1c30",
          "primary": "#004ac6",
          "secondary-container": "#39b8fd",
          "on-secondary-container": "#004666",
          "surface-dim": "#cbdbf5",
          "secondary": "#006591",
          "surface-container-lowest": "#ffffff",
          "surface-container": "#e5eeff",
          "surface-container-low": "#eff4ff",
          "inverse-on-surface": "#eaf1ff",
          "tertiary-fixed-dim": "#c0c1ff",
          "background": "#f8f9ff",
          "on-tertiary": "#ffffff",
          "on-error-container": "#93000a",
          "inverse-primary": "#b4c5ff",
          "on-secondary-fixed-variant": "#004c6e",
          "secondary-fixed-dim": "#89ceff",
          "tertiary-container": "#585be6",
          "primary-fixed-dim": "#b4c5ff",
          "on-secondary": "#ffffff",
          "on-surface": "#0b1c30",
          "surface-tint": "#0053db",
          "on-primary-container": "#eeefff",
          "tertiary-fixed": "#e1e0ff",
          "on-primary-fixed": "#00174b",
          "surface-variant": "#d3e4fe",
          "surface-container-high": "#dce9ff",
          "on-surface-variant": "#434655"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "unit": "4px",
          "container-padding-mobile": "16px",
          "gutter": "24px",
          "container-padding-desktop": "32px",
          "sidebar-width": "260px",
          "table-row-height": "48px"
      },
      "fontFamily": {
          "title-lg": ["Geist"],
          "headline-lg": ["Geist"],
          "body-lg": ["Geist"],
          "display-lg": ["Geist"],
          "label-sm": ["Geist"],
          "title-md": ["Geist"],
          "body-md": ["Geist"],
          "label-md": ["Geist"],
          "headline-md": ["Geist"]
      },
      "fontSize": {
          "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
          "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "600" }],
          "title-md": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
          "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
          "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
          "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
